[build]
  base = "cloth-web"
  command = "yarn build"     # or: npm run build
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "yarn dev"       # or: npm run dev
  targetPort = 5173
  port = 8888
  framework = "#custom"

[functions]
  node_bundler = "esbuild"